name: explore-education-statistics-analytics-$(rev:r)

pool:
  name: RSConnect
  
trigger:
  branches:
    include:
    - main

  paths:
    include:
    - analytics-dashboard/*
    
resources:
  repositories:
    - repository: posit-deploy
      type: git
      name: ESFA-Data-Science/posit-deploy
      
extends:
  template: deploy.yml@posit-deploy
  parameters:
    appName: explore-education-statistics-analytics
    environments:
    - name: Pre-Production
      appId: 
    - name: Production
      appId: 
    approvers: |
     cameron.race@education.gov.uk
     laura.selby@education.gov.uk
     richard.bielby@education.gov.uk
    strategy:
      runOnce:
        preDeploy:
          steps:
          - checkout: self
            path: analytics-dashboard/
